### PR TITLE
fix: limit reduce debt to pallet admin

### LINKED ISSUE #96: Add pallet admin access control to reduce debt
The check for pallet admin origin within `reduce_debt` was removed in 62c46380fd84d924f97311eb7a04b96e16bb6c58 this made sense then since feed balances where tracked for the whole pallet and not on a per feed basis, so allowing any account to reduce debt made sense in this setting.
Now that endowment and debt is tracked on a per feed basis, the `reduce_debt` call should be limited again to the pallet admin to remove the exploit scenario where a malicious oracle calls reduce_debt and causes the pallet admin to pay out more funds than intended.

### PR DESCRIPTION
**Pull request by mattsse**
# Changes
- ensure `reduce_debt` is called by the pallet_admin

# Issues
- Closes #96

### CODE REVIEW

File: pallet-chainlink-feed/src/tests.rs [hunk 1]
```diff
@@ -1210,7 +1210,11 @@ fn can_go_into_debt_and_repay() {
 		assert_eq!(Balances::free_balance(admin), new_funds - 10);
 		assert_eq!(ChainlinkFeed::debt(0).unwrap(), payment - 10);
 		// should be possible to overshoot in passing the amount correcting debt...
-		assert_ok!(ChainlinkFeed::reduce_debt(Origin::signed(42), 0, payment));
+		assert_ok!(ChainlinkFeed::reduce_debt(
```
Comment (ebarakos) [inline pallet-chainlink-feed/src/tests.rs:1213]: Maybe add an extra test @mattsse that shows/asserts that non-admins cannot reduce dept?

**Review by ebarakos — CHANGES_REQUESTED** [review]

File: pallet-chainlink-feed/src/tests.rs (hunk 1 above)
Comment (mattsse) [reply pallet-chainlink-feed/src/tests.rs:1220]: Added a check against non admin

**Review by ebarakos — APPROVED** [review]
